Module8 task1
htmlacademy-ecmascript/1596691-big-trip-14 pull request #14
Opened 2021-05-16 18:35 UTC by alexrocks4

2021-05-17 10:47 UTC, dtsaryov requested changes

2021-05-17 10:47 UTC, dtsaryov commented on src/api.js
> +  _sendRequest({
Приватные методы должны идти после публичных

2021-05-17 10:47 UTC, dtsaryov commented on src/model/destination.js
> +  }
https://up.htmlacademy.ru/ecmascript/14/criteries#d3

2021-05-17 10:47 UTC, dtsaryov commented on src/model/offer.js
> +  getOffers() {
https://up.htmlacademy.ru/ecmascript/14/criteries#d3

2021-05-17 10:47 UTC, dtsaryov commented on src/model/trip-type.js
> +  getTripTypes() {
https://up.htmlacademy.ru/ecmascript/14/criteries#d3

2021-05-17 10:47 UTC, dtsaryov commented on src/model/trip-type.js
> +export default class TripType {
Не очень понял, зачем тебе этот класс

2021-05-17 10:47 UTC, dtsaryov commented on src/request.http
> +GET https://14.ecmascript.pages.academy/big-trip/points HTTP/1.1
Это надо в .gitignore и удалить из гит индекса

2021-05-17 11:08 UTC, alexrocks4 commented on src/model/trip-type.js
> +export default class TripType {
На случай, если в будущем нужно будет получать эти данные с сервера.

2021-05-17 17:51 UTC, merged

2021-06-03 19:36 UTC, dtsaryov commented on src/view/loading.js
> +  return '<p class="trip-events__msg">Loading...</p>';
Давай сделаем функцию однострочной для простоты и экономии места.